# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno fmt, lint, and test.
# For more information see: https://github.com/denoland/setup-deno

name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test --doc

      - name: Generate lcov report
        run: deno coverage cov_profile --lcov --output=cov_profile.lcov

      - name: Upload lcov report
        uses: codecov/codecov-action@v3
        with:
          files: ./cov_profile.lcov
          fail_ci_if_error: true
